services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "80:80"
    depends_on:
      server:
        condition: service_healthy

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    volumes:
    - ./db.json:/data/db.json:rw 
    tmpfs:
    - /data 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 3s
